name: Release CodeNav

on: workflow_dispatch

jobs:
  release-github:
    runs-on: windows-latest
    steps:
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build.yml
        workflow_conclusion: success

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          CodeNav/CodeNav.VS2019/release/Debug/CodeNav.VS2019.vsix
          CodeNav/CodeNav.VS2022/release/Debug/CodeNav.VS2022.vsix

  release-marketplace-vs2019:
    runs-on: windows-latest
    steps:
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build.yml
        workflow_conclusion: success

    - name: Publish extension to Marketplace
      uses: cezarypiatek/VsixPublisherAction@0.1
      with:
        extension-file: CodeNav/CodeNav.VS2019/bin/release/CodeNav.VS2019.vsix
        publish-manifest-file: CodeNav/publish-manifest.VS2019.json
        personal-access-code: ${{ secrets.VS_PUBLISHER_ACCESS_TOKEN }}

  release-marketplace-vs2022:
    runs-on: windows-latest
    steps:
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build.yml
        workflow_conclusion: success

    - name: Publish extension to Marketplace
      uses: cezarypiatek/VsixPublisherAction@0.1
      with:
        extension-file: CodeNav/CodeNav.VS2022/bin/release/CodeNav.VS2022.vsix
        publish-manifest-file: CodeNav/publish-manifest.VS2022.json
        personal-access-code: ${{ secrets.VS_PUBLISHER_ACCESS_TOKEN }}  